# build and deploy from _site
[build]
  publish = "_site"
  command = "pnpm build"

# [[plugins]]
#   package = "@netlify/plugin-sitemap"
#   # https://github.com/netlify-labs/netlify-plugin-sitemap#readme

#   [plugins.inputs]
#   buildDir = "public"
#   exclude = [
#      # By Glob pattern
#     '**/404.html',
#   ]

#   # default is true also
#   prettyURLs = true
#   # Append missing trailing slash to pretty URL, only use if want .html pages to use /
#   trailingSlash = true

# https://www.npmjs.com/package/netlify-plugin-js-obfuscator/v/1.0.20
# [[plugins]]
#   package = "netlify-plugin-js-obfuscator"

# https://www.npmjs.com/package/netlify-plugin-submit-sitemap
[[plugins]]
  package = "netlify-plugin-submit-sitemap"

# https://www.npmjs.com/package/netlify-plugin-11ty
[[plugins]]
    package = "netlify-plugin-11ty"
    [plugins.inputs]
        # eleventy-img outputDir, path relative to publish directory
        cache_img = 'img/'
        cache_img_httpHeader = false

        # eleventy-fetch cacheDir, path relative to publish directory
        cache_assets = '../.cache/'
        # cache_other = []